graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 244
         y 56
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 378
         y 58
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 303
         y 125
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 242
         y 196
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 301
         y 265
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 384
         y 227
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 397
         y 313
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 397
         y 413
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 308
         y 334
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 306
         y 420
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 234
         y 313
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 219
         y 426
      ]
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 12
      label ""
      weight 1.0
   ]
]