graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 456
         y 160
      ]
   ]
   node [
      id 1
      label "A"
      graphics [
         x 661
         y 160
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 661
         y 286
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 446
         y 287
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 443
         y 417
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 675
         y 427
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 2
      label ""
      weight 1.0
   ]
]